# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ff73bf4f7677126e1b1eb0308ff097e286e647eb7ee80c894cd94547baf5a9b063ac2516b1043bdc48b8cdf98ea465ca74a353b5fd807646e5d9310da333687

test:
  secret_key_base: e8fe1ccdcc343cb38c8b9d3e6b3cb73c34893c19a255539733efa860a74bddff05e1f8bc862d9fc97dd44bba1bc833de237da0e6aeaafc61edb756486c04da5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
